extends SceneTree
## 실행: godot --headless --path . --script res://village_sim/tools/ai_lab_v4_smoke_test.gd
const DataLoader = preload("res://village_sim/scripts/data/data_loader.gd")
const Runner = preload("res://village_sim/scripts/ai/training_runner.gd")

func _init() -> void:
	var data: Dictionary = DataLoader.new().load_all()
	assert(data.get("load_errors", []).is_empty(), "데이터 로드 실패")
	var initial_stats: Array = data["config"]["stats"]
	assert(int(initial_stats[0]["initial"]) == 50 and int(initial_stats[1]["initial"]) == 50, "본편 시작 자원 설정 불일치")
	assert(int(initial_stats[2]["initial"]) == 55 and int(initial_stats[3]["initial"]) == 50, "본편 시작 자원 설정 불일치")
	assert(float(data["config"]["effect_scale"]["finance"]["loss"]) > 1.0, "손실 강화 설정 누락")
	var runner = Runner.new(data)
	runner.configure("normal", "balance")
	runner.reset()
	var normal: Dictionary = runner._data_for_scenario("normal")
	assert(int(normal["config"]["stats"][0]["initial"]) == 50, "일반 실험 마을과 본편 난이도가 다름")
	var treasury: Dictionary = runner._data_for_scenario("treasury")
	assert(int(treasury["config"]["stats"][1]["initial"]) == 28, "재정 위기 마을 설정 오류")
	var dual: Dictionary = runner._data_for_scenario("dual")
	assert(int(dual["config"]["stats"][1]["initial"]) == 35 and int(dual["config"]["stats"][2]["initial"]) == 30, "복합 위기 설정 오류")
	assert(int(data["config"]["stats"][1]["initial"]) == 50, "미션 설정이 원본 데이터를 변경함")
	runner.train_until(10)
	assert(runner.trained == 10, "10판 학습 실패")
	var old_weights: Array = runner.agent.weights.duplicate()
	var old_snapshots := runner.weight_snapshots.size()
	runner.configure("treasury", "rescue")
	assert(runner.trained == 10 and runner.agent.weights == old_weights, "훈련 환경/보상 변경 시 학습 초기화")
	assert(runner.weight_snapshots.size() == old_snapshots, "과거 학습 기록이 사라짐")
	runner.train_until(14)
	assert(runner.trained == 14 and runner.weight_snapshots.size() == old_snapshots + 1, "설정 변경 후 추가 학습 실패")
	runner.configure("mixed", "survival")
	assert(runner.trained == 14, "보상 목표 변경 뒤 총 훈련 수 손실")
	var report: Dictionary = runner.evaluate("normal")
	assert(report["random"]["runs"] == 120, "기존 동등 조건 평가 오류")
	assert(not runner.learning_report(report).is_empty(), "학습 결과 설명 생성 실패")
	var watch: Dictionary = runner.watch_example("normal")
	assert(not watch["decisions"].is_empty(), "AI 판단 보기 실패")
	runner.reset()
	assert(runner.trained == 0 and runner.weight_snapshots.size() == 1, "명시적 초기화 실패")
	print("PASS v5: 손실 강화 난이도, 미션 분리, 학습 보존, AI 배운 점 요약, 평가/판단 기록")
	quit()
